### ISSUE TITLE
make sure outputs like  the kernel etc. from `sel4-sys` are directly under `target/<triple>/sel4`

### ISSUE THREAD

**Issue by wucke13** [DLR-FT/sel4-rs#5]
https://doc.rust-lang.org/cargo/reference/environment-variables.html

`CARGO_TARGET_DIR` seems to be hot candidate for this.

**Comment by moritz-meier** [comment]
Update: exists in https://github.com/moritz-meier/sel4-rs/tree/feature/external-sel4-build

**Comment by moritz-meier** [comment]
done.
